# Prose.io configuration
prose:
  siteurl: "http://howwehavebeensavingtheplanetthisweek.com"
  media: "media"
  metadata:
    newsletters:
      - name: "subject"
        field:
          element: "text"
          label: "Subject Line"
      - name: "teaser"
        field:
          element: "text"
          label: "Emoji Teaser"

# Jekyll configuration
baseurl: http://howwehavebeensavingtheplanetthisweek.com
defaults:
  -
    scope:
      path: "newsletters"
    values:
      layout: "newsletter"
