baseurl: "http://www.howwehavebeensavingtheplanetthisweek.com/"

# Prose.io configuration
prose:
  siteurl: "http://www.howwehavebeensavingtheplanetthisweek.com"
  media: "media"
  metadata:
    newsletters:
      - name: "subject"
        field:
          element: "text"
          label: "Subject Line"
      - name: "teaser"
        field:
          element: "text"
          label: "Emoji Teaser"

# Jekyll configuration
defaults:
  -
    scope:
      path: "newsletters"
    values:
      layout: "newsletter"
  -
    scope:
      path: ""
    values:
      layout: "markdown"
exclude: ["CNAME", "readme.md", "README.md","Gemfile","Gemfile.lock","circle.yml","vendor"]

# GitHub Pages configuration
gems:
- jemoji
- jekyll-redirect-from
- jekyll-mentions

jekyll-mentions:
  base_url: https://twitter.com
